### ISSUE TITLE
possible incompatibility between sente and clojure/tools.namespace refresh

### ISSUE THREAD

**Issue by rwat** [ptaoussanis/sente#250]
I've used previous versions of sente to good effect but the version 1.10.0 in conjunction with clojure/tools.namespace 0.2.11 (and 0.3.0-alpha1) and compiled clojurescript (I've tested under optimizations :none, :whitespace and :simple) produce the following truss related error when a clojure/tools.namespace refresh is done:

```
my-project.core=> (refresh)
:reloading ((... many project libraries ...) taoensso.sente.interfaces taoensso.sente (... more project libraries ...))
:error-while-loading my-project.web.core
#error {
 :cause "Invariant violation in `taoensso.sente:?` [pred-form, val]:\n [((fn* [p1__25230#] (satisfies? interfaces/IServerChanAdapter p1__25230#)) web-server-ch-adapter), taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter@3843d51d]"
 :data {:*?data* nil, :elidable? true, :dt #inst "2016-07-29T13:57:38.451-00:00", :val #object[taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter 0x3843d51d "taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter@3843d51d"], :ns-str "taoensso.sente", :val-type taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter, :?err nil, :*assert* true, :?data nil, :?line nil, :form-str "((fn* [p1__25230#] (satisfies? interfaces/IServerChanAdapter p1__25230#)) web-server-ch-adapter)"}
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message "clojure.lang.ExceptionInfo: Invariant violation in `taoensso.sente:?` [pred-form, val]:\n [((fn* [p1__25230#] (satisfies? interfaces/IServerChanAdapter p1__25230#)) web-server-ch-adapter), taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter@3843d51d] {:*?data* nil, :elidable? true, :dt #inst \"2016-07-29T13:57:38.451-00:00\", :val #object[taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter 0x3843d51d \"taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter@3843d51d\"], :ns-str \"taoensso.sente\", :val-type taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter, :?err nil, :*assert* true, :?data nil, :?line nil, :form-str \"((fn* [p1__25230#] (satisfies? interfaces/IServerChanAdapter p1__25230#)) web-server-ch-adapter)\"}, compiling:(my-project/web/core.clj:12:1)"
   :at [clojure.lang.Compiler load "Compiler.java" 7391]}
  {:type clojure.lang.ExceptionInfo
   :message "Invariant violation in `taoensso.sente:?` [pred-form, val]:\n [((fn* [p1__25230#] (satisfies? interfaces/IServerChanAdapter p1__25230#)) web-server-ch-adapter), taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter@3843d51d]"
   :data {:*?data* nil, :elidable? true, :dt #inst "2016-07-29T13:57:38.451-00:00", :val #object[taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter 0x3843d51d "taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter@3843d51d"], :ns-str "taoensso.sente", :val-type taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter, :?err nil, :*assert* true, :?data nil, :?line nil, :form-str "((fn* [p1__25230#] (satisfies? interfaces/IServerChanAdapter p1__25230#)) web-server-ch-adapter)"}
   :at [clojure.core$ex_info invokeStatic "core.clj" 4617]}]
 :trace
 [[clojure.core$ex_info invokeStatic "core.clj" 4617]
  [clojure.core$ex_info invoke "core.clj" 4617]
  [taoensso.truss.impl$default_error_fn invokeStatic "impl.clj" 51]
  [taoensso.truss.impl$default_error_fn invoke "impl.clj" 49]
  [taoensso.truss.impl$_invar_violation_BANG_ invokeStatic "impl.clj" 147]
  [taoensso.truss.impl$_invar_violation_BANG_ invoke "impl.clj" 142]
  [taoensso.sente$make_channel_socket_server_BANG_ invokeStatic "sente.cljc" 292]
  [taoensso.sente$make_channel_socket_server_BANG_ doInvoke "sente.cljc" 245]
  [clojure.lang.RestFn invoke "RestFn.java" 423]
  [my-project.web.core$eval25910 invokeStatic "core.clj" 14]
  [my-project.web.core$eval25910 invoke "core.clj" 12]
  [clojure.lang.Compiler eval "Compiler.java" 6927]
  [clojure.lang.Compiler load "Compiler.java" 7379]
  [clojure.lang.RT loadResourceScript "RT.java" 372]
  [clojure.lang.RT loadResourceScript "RT.java" 363]
  [clojure.lang.RT load "RT.java" 453]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__5677 invoke "core.clj" 5893]
  [clojure.core$load invokeStatic "core.clj" 5892]
  [clojure.core$load doInvoke "core.clj" 5876]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [clojure.core$load_one invokeStatic "core.clj" 5697]
...
```

Something I find interesting is that if I delete the contents of the target directory for clojurescript compilation (I have cljsbuild pointing at resources/public/js/build) then a clojure/tools.namespace refresh /will not/ attempt to refresh taoensso.sente.interfaces taoensso.sente and therefore won't throw the above error.  The error is only thrown after a clojurescript compile.

**Comment by rwat** [comment]
I read the source for clojure/tools.namespace and the above error can be avoided by only having clojure.tools.namespace.repl/refresh look at my clojure code directory and staying away from compiled clojurescript.  The following function restricts 'refresh' to only the supplied directories:

(clojure.tools.namespace.repl/set-refresh-dirs "clj")

Imho, this is an entirely satisfactory work-around to the problem.

**Comment by ptaoussanis** [comment]
Thanks for following up!

**Comment by kajism** [comment]
I have met this error today. We have src/cljs and src/cljc directories in our project, but clj files start in the src, so the above solution is not so satisfactory. I'm wondering if this is a bug of clojure.tools.namespace (I use 0.3.0-alpha3) or how else to fix it?

Side note: I tried to upgrade sente, because of a long term struggle with sente and "reloaded workflow". The connection is lost (requests timeout) after server-side reload/refresh. We have to reload the client in the browser to reconnect.

Thanks for any comments

**Comment by rwat** [comment]
Regarding your Side Note and the request timeout after server-side refresh, because clojure.tools.namespace.repl/refresh destroys global vars are you shutting down httpkit per their instructions [1] prior to running refresh?

Regarding your primary issue, apart from getting refresh and truss to play together nicely, you could try forking the sente repo and commenting out line 311 of sente/src/taoensso/sente.cljc:

(have? #(satisfies? interfaces/IServerChanAdapter %) web-server-ch-adapter)

That appears to be the problem.  I haven't tried it myself because of the workaround I posted earlier (with my split clojure / clojurescript code base)

---
1. http://www.http-kit.org/server.html#stop-server

**Comment by kajism** [comment]
Concerning this issue exception:
The refresh works without problems when I clone current HEAD of sente into our project's checkouts dir, so it's hard to test commenting out the truss/satisfies? line...

Concerning the side note:
You are right, we were not shutting down http-kit properly at refresh, because in our home baked http-kit component we implemented Suspendable interface inspired by ring-jetty-component. Not a good idea in this scenario. Thanks a lot, works great now!

**Comment by zane** [comment]
I'm also experiencing this issue. The workaround of restricting the directories passed to `clojure.tools.namespace.repl/set-refresh-dirs` is difficult in my case because I'm using [Boot](http://boot-clj.com/) and Boot's pods system obfuscates source directory names. This is all fixable of course, but if this is fixed on `master` it'd be wonderful to get a new point release (or new `SNAPSHOT`) out to Clojars.

**Comment by ptaoussanis** [comment]
> This is all fixable of course, but if this is fixed on master it'd be wonderful to get a new point release (or new SNAPSHOT) out to Clojars.

Sorry, just to clarify: fixed on Sente master? What change are you suggesting exactly?

Cheers :-)

**Comment by nha** [comment]
Maybe a section in the README would be useful though.
Something like the following?

# Incompatibilities and workarounds
 - clojure.tools.namespace 0.2.11 (and 0.3.0-alpha1) and compiled clojurescript when refreshing , see https://github.com/ptaoussanis/sente/issues/250

**Comment by nha** [comment]
@zane I also use boot, and this does not impact the way the workaround above work for me.

**Comment by zane** [comment]
Sorry for the delay. @ptaoussanis, it just sounded like it was fixed on Sente's `master` branch. I was hoping for a new Sente release that included the fix. Thank you so much for your work on this library!

**Comment by lxsameer** [comment]
@ptaoussanis hi. first of all, Kudos. I ran to the same problem, did you manage to release a new version based on master branch on clojars ?

**Comment by lxsameer** [comment]
I tested my code with the current master, the issue still exists. here is the exception I'm getting:

```
clojure.lang.ExceptionInfo: Invariant violation in `taoensso.sente:?`. Test form: `((fn* [p1__33672#] (satisfies? interfaces/IServerChanAdapter p1__33672#)) web-server-ch-adapter)` with failing input: `taoensso.sente.server_adapters.immutant.ImmutantServerChanAdapter@69ed0e1c`
```

**Comment by royalaid** [comment]
Just curious as to the status of this issue, pulled down the repo and installed to get the latest commits on master and tried the `(set-refresh-dirs "clj")` to no avail.

**Comment by kaosko** [comment]
In a mixed clojure/java project and using Virgil (to reload the Java code), I seem to get into this state sometimes when I restart the (dev) server with existing target directory. Virgil causes reloading the clj code but if I "lein clean" first, it always starts up (despite the initial reloads).

**Comment by eerohele** [comment]
I believe this issue is caused by [TNS-45](https://dev.clojure.org/jira/browse/TNS-45).
